# Generated by Django 3.1.7 on 2021-03-23 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chirps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chirp',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ChirpLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chirp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chirps.chirp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chirp',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='chirp_user', through='chirps.ChirpLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
