# Generated by Django 3.1.7 on 2021-03-24 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chirps', '0002_auto_20210323_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='chirp',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chirps.chirp'),
        ),
        migrations.AlterField(
            model_name='chirp',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
